apiVersion: v1
description: Deploys Errbit. Errbit is a tool for collecting and managing errors from other applications
name: errbit-helm
version: 0.4.2
sources:
  - https://github.com/zhum/errbit-helm
  - https://github.com/errbit/errbit
icon: https://errbit.com/images/apps.png
